services: 

  elinity_common:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: elinity_common:latest
    container_name: elinity_common
    ports:
      - "8081:8081"
    environment:
      - PYTHONPATH=/app
    command: uvicorn main:app --host 0.0.0.0 --port 8081 

    networks:
      - elinity_common_default
    volumes:
      - ./:/app

  celery_worker_elinity:
    container_name: elinity_celery_worker
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: celery_worker:latest
    command: celery -A core.celery.celery_app worker --loglevel=info
    depends_on:
      - elinity_common
    networks:
      - elinity_common_default
    volumes:
      - ./:/app 
  
  celery_beat_elinity:
    container_name: elinity_celery_beat
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: celery_beat:latest
    command: celery -A core.celery.celery_app beat --loglevel=info
    depends_on:
      - elinity_common
    networks:
      - elinity_common_default
    volumes:
      - ./:/app 
    
networks:
  elinity_common_default: 
    driver: bridge 
